language: node_js
node_js:
- '8'
install: npm install && npm run install:fe
script: npm run lint && npm test
before_deploy: npm run build:fe
deploy:
  provider: npm
  email: ahui-lin@qq.com
  skip_cleanup: true
  api_key:
    secure: h9b9VryX3LPUVgTECVy+8c9zs4FOTwxOAJXJ4l1+zQVXRkE3sxpXigKjg7ma9+lFkqQiOQxZ1d6JstjklWgSczOLiiKsutSGL+DPCsvfZqp2jN+ZlEVTYyPU+1/AjL2hD617LnJTVABl01uL+w27dM5w/J8TCoUi3Hu4lN1no/xwM7cdyUWKvo4O+S65M7+a7uMMPnqr6t/KGRBVhYe1tnQgWLLRHXYLEXX1Exi+R70Lk0pNxyc79JV19FlGzs1gJOczNIEQOwFkxnL1hXM+jCdynfoKv0ifiox20cflLSqq+e4WMEC0yq3vSMS+sdxZBFbe7V9en9qkZ7rcarlct5yLJtAkDtX3oR6sNNPAD0mrKeBEgEm+bZjh8MoFK6rNG+/GsHpiLG52nUE/dzubdjSw6R18V7T9jOgT73HX+1prNR79cCA1A56BkDiNqTdZ5HpnshO20V+DUeyrS2Nxudj0gvAtBtOsJ+eqqdLJ4hti+dDZqwMc/GOiU6SDqAaO/wimcaqXezBaDpOexyJRlBiqTEfWuVYC9JBS09ME2BOhU3NLRHJHZMyAwQp73+CavWyTwx//WtApTcF1q1KM0WM9a+b7PeNlzPngk68xR7COeC0ESy/4Zqz49qUnjeYmvAIwlMzpJriI4+lZZLgyhmRcSIRG8hFS8sN1XbVE+eg=
  on:
    tags: true
